* source code is now in src/  * translations are now in po/  * directory doxygen/  * split of Makefile

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -104,7 +104,7 @@ SHELL=${CONFIG_SHELL-/bin/sh}
 # only ac_max_sed_lines should be used.
 : ${ac_max_here_lines=38}
 
-ac_unique_file="hamfax.cpp"
+ac_unique_file="src/hamfax.cpp"
 
 # Initialize some variables set by options.
 ac_init_help=
@@ -3173,7 +3173,7 @@ fi
 echo "$as_me:3173: result: $ac_cv_header_sys_soundcard_h" >&5
 echo "${ECHO_T}$ac_cv_header_sys_soundcard_h" >&6
 
-ac_config_files="$ac_config_files Makefile"
+ac_config_files="$ac_config_files Makefile src/Makefile po/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -3506,7 +3506,9 @@ do
   case "$ac_config_target" in
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
-  *) { { echo "$as_me:3509: error: invalid argument: $ac_config_target" >&5
+  "src/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
+  "po/Makefile" ) CONFIG_FILES="$CONFIG_FILES po/Makefile" ;;
+  *) { { echo "$as_me:3511: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -3719,7 +3721,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:3722: creating $ac_file" >&5
+    { echo "$as_me:3724: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -3737,7 +3739,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:3740: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:3742: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -3750,7 +3752,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:3753: error: cannot find input file: $f" >&5
+           { { echo "$as_me:3755: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
